name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven Wrapper
        run: ./mvnw clean install

      - name: Generate coverage report
        run: ./mvnw test jacoco:report

      - name: Run SonarScanner
        uses: sonarsource/sonar-scanner-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://sonarcloud.io"
        with:
          projectBaseDir: .
          args: >
            -Dsonar.organization=SITAS-QA
            -Dsonar.projectKey=SITAS-QA_SITAS-Back-QA
            -Dsonar.sources=.
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
